import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientWrapper from "shared/components/ClientWrapper";
import "shared/styles/main.css";
import "shared/styles/utopia.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>{children}</ClientWrapper>
      </body>
    </html>
  );
}
